"""empty message

Revision ID: a635111b6a27
Revises: 
Create Date: 2022-11-10 08:56:33.930729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a635111b6a27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('option_alt', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.Column('lng', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('late_bus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('late_bus')
    op.drop_table('school')
    # ### end Alembic commands ###
